//! UTS #51 Emoji character properties (`emoji-data.txt`).
//!
//! Six independent boolean properties are defined for emoji processing. A code
//! point may carry any combination of them (e.g. U+231A WATCH is both `Emoji`
//! and `Emoji_Presentation`; an ASCII digit is `Emoji` and `Emoji_Component`
//! but not `Extended_Pictographic`):
//!
//! - **Emoji** — characters that are emoji.
//! - **Emoji_Presentation** — emoji that default to an emoji (rather than text)
//!   presentation.
//! - **Emoji_Modifier** — the five skin-tone modifiers (U+1F3FB..U+1F3FF).
//! - **Emoji_Modifier_Base** — emoji that can take a skin-tone modifier.
//! - **Emoji_Component** — characters used in emoji sequences that are not
//!   normally standalone emoji (skin-tone modifiers, regional indicators, ZWJ,
//!   keycap pieces, tag characters, …).
//! - **Extended_Pictographic** — a superset used by UAX #29 grapheme clustering
//!   (rule GB11, the ZWJ emoji sequence rule). Includes unassigned reserved
//!   ranges so future pictographs cluster correctly.
//!
//! Per-code-point lookups resolve through the generated tables in `generated/`
//! (a deduplicated two-level page table for the large properties, a sorted range
//! list for the small ones). For consumers that must *enumerate* a property into
//! sorted code-point ranges at comptime — a regex engine resolving `\p{Emoji}`,
//! say — the `*_runs` slices give that without walking all 1.1M code points; see
//! `scripts.script_runs` for the same pattern.

const std = @import("std");
const encoding = @import("encoding");

const CodePoint = encoding.CodePoint;

/// Generated emoji property tables (UTS #51): the deduplicated two-level page
/// tables for the dense properties and sorted range lists for the sparse ones,
/// plus the `is*` predicates. Re-exported so callers can reach the raw tables
/// without importing the `generated/` path directly.
pub const generated = @import("generated/emoji_data.zig");
/// Sorted emoji range tables. Enumerable at comptime, unlike the per-code-point
/// page tables, so consumers can resolve `\p{Emoji}`, `\p{Extended_Pictographic}`,
/// etc. into code-point ranges. Generated by `zig build generate-ranges`.
pub const generated_ranges = @import("generated/emoji_ranges.zig");

// ── Per-code-point predicates ────────────────────────────────────────────────
// Thin re-exports of the generated lookups, given their doc comments and
// `@stable-since` tag here at the module boundary (the generated file is
// overwritten by `zig build generate` and carries no annotations of its own).

/// Emoji(cp) (UTS #51): reports whether `cp` is an emoji character. Out-of-range
/// code points return `false`. Note this includes the ASCII digits, `#`, and `*`
/// (the keycap bases), which are emoji only in a sequence.
///
/// @stable-since: v0.3.0
pub const isEmoji = generated.isEmoji;
/// Emoji_Presentation(cp) (UTS #51): reports whether `cp` defaults to an emoji
/// (rather than text) presentation. Out-of-range code points return `false`.
///
/// @stable-since: v0.3.0
pub const isEmojiPresentation = generated.isEmojiPresentation;
/// Emoji_Modifier(cp) (UTS #51): reports whether `cp` is one of the five
/// skin-tone modifiers (U+1F3FB..U+1F3FF). Out-of-range returns `false`.
///
/// @stable-since: v0.3.0
pub const isEmojiModifier = generated.isEmojiModifier;
/// Emoji_Modifier_Base(cp) (UTS #51): reports whether `cp` can take a skin-tone
/// modifier. Out-of-range code points return `false`.
///
/// @stable-since: v0.3.0
pub const isEmojiModifierBase = generated.isEmojiModifierBase;
/// Emoji_Component(cp) (UTS #51): reports whether `cp` is used as a component of
/// emoji sequences (skin-tone modifiers, regional indicators, ZWJ, keycap
/// pieces, tag characters, …). Out-of-range returns `false`.
///
/// @stable-since: v0.3.0
pub const isEmojiComponent = generated.isEmojiComponent;
/// Extended_Pictographic(cp) (UTS #51): reports whether `cp` has the
/// Extended_Pictographic property, the superset used by UAX #29 grapheme
/// clustering (rule GB11). Includes reserved/unassigned ranges. Out-of-range
/// code points return `false`.
///
/// @stable-since: v0.3.0
pub const isExtendedPictographic = generated.isExtendedPictographic;

// ── Combined / enumerated query API ──────────────────────────────────────────

/// One of the six UTS #51 emoji properties. The tag order matches the field
/// order of `EmojiProperties` and the `*_runs` accessors.
///
/// @stable-since: v0.3.0
pub const EmojiProperty = enum {
    emoji,
    emoji_presentation,
    emoji_modifier,
    emoji_modifier_base,
    emoji_component,
    extended_pictographic,
};

/// The full set of UTS #51 emoji properties of a single code point, one bool per
/// property. Produced by `emojiProperties`; `any()` reports whether at least one
/// property is set.
///
/// @stable-since: v0.3.0
pub const EmojiProperties = packed struct {
    emoji: bool = false,
    emoji_presentation: bool = false,
    emoji_modifier: bool = false,
    emoji_modifier_base: bool = false,
    emoji_component: bool = false,
    extended_pictographic: bool = false,

    /// True if `cp` carries at least one emoji property.
    pub inline fn any(self: EmojiProperties) bool {
        return self.emoji or self.emoji_presentation or self.emoji_modifier or
            self.emoji_modifier_base or self.emoji_component or self.extended_pictographic;
    }
};

/// Reports whether `cp` has the given emoji `property`. A uniform dispatcher over
/// the six predicates, useful when the property is selected at runtime.
///
/// @stable-since: v0.3.0
pub inline fn hasEmojiProperty(cp: CodePoint, property: EmojiProperty) bool {
    return switch (property) {
        .emoji => isEmoji(cp),
        .emoji_presentation => isEmojiPresentation(cp),
        .emoji_modifier => isEmojiModifier(cp),
        .emoji_modifier_base => isEmojiModifierBase(cp),
        .emoji_component => isEmojiComponent(cp),
        .extended_pictographic => isExtendedPictographic(cp),
    };
}

/// Resolves all six emoji properties of `cp` in one call. Each field is the
/// result of the corresponding `is*` predicate. Out-of-range code points yield
/// an all-`false` struct.
///
/// @stable-since: v0.3.0
pub inline fn emojiProperties(cp: CodePoint) EmojiProperties {
    return .{
        .emoji = isEmoji(cp),
        .emoji_presentation = isEmojiPresentation(cp),
        .emoji_modifier = isEmojiModifier(cp),
        .emoji_modifier_base = isEmojiModifierBase(cp),
        .emoji_component = isEmojiComponent(cp),
        .extended_pictographic = isExtendedPictographic(cp),
    };
}

/// True if `cp` carries any of the six emoji properties. Equivalent to
/// `emojiProperties(cp).any()` but short-circuits over the cheap predicates.
///
/// @stable-since: v0.3.0
pub inline fn hasAnyEmojiProperty(cp: CodePoint) bool {
    return isEmoji(cp) or isEmojiPresentation(cp) or isEmojiModifier(cp) or
        isEmojiModifierBase(cp) or isEmojiComponent(cp) or isExtendedPictographic(cp);
}

// ── Enumerable range tables (sorted, comptime-walkable) ───────────────────────

/// One inclusive `[start, end]` run of code points sharing an emoji property.
///
/// @stable-since: v0.3.0
pub const EmojiRange = generated_ranges.Range;

/// Emoji ranges, sorted by `start`. Enumerates `isEmoji`.
///
/// @stable-since: v0.3.0
pub const emoji_ranges: []const EmojiRange = &generated_ranges.emoji_ranges;
/// Emoji_Presentation ranges, sorted by `start`. Enumerates `isEmojiPresentation`.
///
/// @stable-since: v0.3.0
pub const emoji_presentation_ranges: []const EmojiRange = &generated_ranges.emoji_presentation_ranges;
/// Emoji_Modifier ranges, sorted by `start`. Enumerates `isEmojiModifier`.
///
/// @stable-since: v0.3.0
pub const emoji_modifier_ranges: []const EmojiRange = &generated_ranges.emoji_modifier_ranges;
/// Emoji_Modifier_Base ranges, sorted by `start`. Enumerates `isEmojiModifierBase`.
///
/// @stable-since: v0.3.0
pub const emoji_modifier_base_ranges: []const EmojiRange = &generated_ranges.emoji_modifier_base_ranges;
/// Emoji_Component ranges, sorted by `start`. Enumerates `isEmojiComponent`.
///
/// @stable-since: v0.3.0
pub const emoji_component_ranges: []const EmojiRange = &generated_ranges.emoji_component_ranges;
/// Extended_Pictographic ranges, sorted by `start`. Enumerates
/// `isExtendedPictographic`.
///
/// @stable-since: v0.3.0
pub const extended_pictographic_ranges: []const EmojiRange = &generated_ranges.extended_pictographic_ranges;

/// Returns the sorted range table backing the given emoji `property`. The slices
/// can be enumerated at comptime, unlike the per-code-point predicates.
///
/// @stable-since: v0.3.0
pub fn rangesFor(property: EmojiProperty) []const EmojiRange {
    return switch (property) {
        .emoji => emoji_ranges,
        .emoji_presentation => emoji_presentation_ranges,
        .emoji_modifier => emoji_modifier_ranges,
        .emoji_modifier_base => emoji_modifier_base_ranges,
        .emoji_component => emoji_component_ranges,
        .extended_pictographic => extended_pictographic_ranges,
    };
}

// ============================================================================
// Tests — representative examples, hostile inputs, and table/predicate parity.
// ============================================================================

const testing = std.testing;

test "isEmoji: representative emoji, ASCII keycap bases, and rejections" {
    try testing.expect(isEmoji(0x231A)); // WATCH
    try testing.expect(isEmoji(0x1F600)); // GRINNING FACE
    try testing.expect(isEmoji(0x1F468)); // MAN
    // ASCII digits, '#', '*' are Emoji (keycap bases) even though they render as
    // text by default.
    try testing.expect(isEmoji('0'));
    try testing.expect(isEmoji('9'));
    try testing.expect(isEmoji('#'));
    try testing.expect(isEmoji('*'));
    // Plain letters and a space are not.
    try testing.expect(!isEmoji('A'));
    try testing.expect(!isEmoji('z'));
    try testing.expect(!isEmoji(' '));
}

test "isEmojiPresentation: defaults-to-emoji vs defaults-to-text" {
    try testing.expect(isEmojiPresentation(0x231A)); // WATCH — emoji default
    try testing.expect(isEmojiPresentation(0x1F600)); // GRINNING FACE
    // Emoji but text-default: digits, '#', '*', COPYRIGHT.
    try testing.expect(!isEmojiPresentation('0'));
    try testing.expect(!isEmojiPresentation('#'));
    try testing.expect(!isEmojiPresentation(0x00A9)); // COPYRIGHT SIGN
    try testing.expect(!isEmojiPresentation('A'));
}

test "isEmojiModifier: exactly the five skin-tone modifiers" {
    var cp: CodePoint = 0x1F3FB;
    while (cp <= 0x1F3FF) : (cp += 1) try testing.expect(isEmojiModifier(cp));
    try testing.expect(!isEmojiModifier(0x1F3FA)); // just below the run
    try testing.expect(!isEmojiModifier(0x1F400)); // just above the run
    try testing.expect(!isEmojiModifier(0x1F600));
    try testing.expect(!isEmojiModifier('a'));
}

test "isEmojiModifierBase: takes a skin tone; modifiers themselves do not" {
    try testing.expect(isEmojiModifierBase(0x1F476)); // BABY
    try testing.expect(isEmojiModifierBase(0x1F468)); // MAN
    try testing.expect(isEmojiModifierBase(0x261D)); // INDEX POINTING UP
    // The modifiers are components, not bases.
    try testing.expect(!isEmojiModifierBase(0x1F3FB));
    try testing.expect(!isEmojiModifierBase('A'));
}

test "isEmojiComponent: modifiers, regional indicators, ZWJ, keycaps" {
    try testing.expect(isEmojiComponent(0x1F3FB)); // skin-tone modifier
    try testing.expect(isEmojiComponent(0x1F1E6)); // REGIONAL INDICATOR A
    try testing.expect(isEmojiComponent(0x1F1FF)); // REGIONAL INDICATOR Z
    try testing.expect(isEmojiComponent(0x200D)); // ZERO WIDTH JOINER
    try testing.expect(isEmojiComponent('0')); // keycap digit
    try testing.expect(isEmojiComponent('#'));
    try testing.expect(!isEmojiComponent('A'));
}

test "isExtendedPictographic: superset incl. text-default symbols" {
    try testing.expect(isExtendedPictographic(0x00A9)); // COPYRIGHT SIGN
    try testing.expect(isExtendedPictographic(0x1F600)); // GRINNING FACE
    try testing.expect(isExtendedPictographic(0x1F468)); // MAN
    try testing.expect(isExtendedPictographic(0x1F469)); // WOMAN
    // Digits are Emoji but NOT Extended_Pictographic.
    try testing.expect(!isExtendedPictographic('0'));
    try testing.expect(!isExtendedPictographic('A'));
}

test "all predicates: out-of-range and surrogates never trap, return false" {
    const hostile = [_]CodePoint{ 0x110000, 0x1FFFFF, 0xD800, 0xDFFF, 0x10FFFF };
    for (hostile) |cp| {
        // 0x10FFFF is in range but unassigned for emoji; the rest are invalid.
        try testing.expect(!isEmoji(cp) or cp == 0x10FFFF);
        // None of these should be emoji at all in practice:
        try testing.expect(!isEmoji(cp));
        try testing.expect(!isEmojiPresentation(cp));
        try testing.expect(!isEmojiModifier(cp));
        try testing.expect(!isEmojiModifierBase(cp));
        try testing.expect(!isEmojiComponent(cp));
        try testing.expect(!isExtendedPictographic(cp));
        try testing.expect(!hasAnyEmojiProperty(cp));
    }
}

test "every code point resolves without trapping across all predicates" {
    var cp: CodePoint = 0;
    while (cp <= 0x10FFFF) : (cp += 1) {
        _ = isEmoji(cp);
        _ = isEmojiPresentation(cp);
        _ = isEmojiModifier(cp);
        _ = isEmojiModifierBase(cp);
        _ = isEmojiComponent(cp);
        _ = isExtendedPictographic(cp);
    }
}

test "Emoji_Presentation ⊆ Emoji and Emoji_Modifier ⊆ Emoji_Component (UTS #51 invariants)" {
    var cp: CodePoint = 0;
    while (cp <= 0x10FFFF) : (cp += 1) {
        if (isEmojiPresentation(cp)) try testing.expect(isEmoji(cp));
        if (isEmojiModifier(cp)) try testing.expect(isEmojiComponent(cp));
        if (isEmojiModifierBase(cp)) try testing.expect(isEmoji(cp));
    }
}

test "hasEmojiProperty dispatches to the matching predicate" {
    try testing.expect(hasEmojiProperty(0x231A, .emoji));
    try testing.expect(hasEmojiProperty(0x231A, .emoji_presentation));
    try testing.expect(hasEmojiProperty(0x1F3FB, .emoji_modifier));
    try testing.expect(hasEmojiProperty(0x1F476, .emoji_modifier_base));
    try testing.expect(hasEmojiProperty(0x1F1E6, .emoji_component));
    try testing.expect(hasEmojiProperty(0x00A9, .extended_pictographic));
    try testing.expect(!hasEmojiProperty('A', .emoji));
}

test "emojiProperties matches the individual predicates for every code point" {
    var cp: CodePoint = 0;
    while (cp <= 0x10FFFF) : (cp += 1) {
        const p = emojiProperties(cp);
        try testing.expectEqual(isEmoji(cp), p.emoji);
        try testing.expectEqual(isEmojiPresentation(cp), p.emoji_presentation);
        try testing.expectEqual(isEmojiModifier(cp), p.emoji_modifier);
        try testing.expectEqual(isEmojiModifierBase(cp), p.emoji_modifier_base);
        try testing.expectEqual(isEmojiComponent(cp), p.emoji_component);
        try testing.expectEqual(isExtendedPictographic(cp), p.extended_pictographic);
        try testing.expectEqual(hasAnyEmojiProperty(cp), p.any());
    }
}

fn expectRangesMatchProperty(ranges: []const EmojiRange, property: EmojiProperty) !void {
    // Sorted, non-empty, non-overlapping, and non-adjacent (maximal runs).
    var prev_end: i64 = -2;
    for (ranges) |r| {
        try testing.expect(r.start <= r.end);
        try testing.expect(@as(i64, r.start) > prev_end + 1);
        prev_end = r.end;
    }
    // Exhaustive parity: the range table flags exactly the code points the
    // predicate does.
    var cp: CodePoint = 0;
    while (cp <= 0x10FFFF) : (cp += 1) {
        var in_ranges = false;
        for (ranges) |r| {
            if (cp >= r.start and cp <= r.end) {
                in_ranges = true;
                break;
            }
        }
        try testing.expectEqual(hasEmojiProperty(cp, property), in_ranges);
    }
}

test "range tables: each is sorted and exactly enumerates its predicate" {
    try expectRangesMatchProperty(emoji_ranges, .emoji);
    try expectRangesMatchProperty(emoji_presentation_ranges, .emoji_presentation);
    try expectRangesMatchProperty(emoji_modifier_ranges, .emoji_modifier);
    try expectRangesMatchProperty(emoji_modifier_base_ranges, .emoji_modifier_base);
    try expectRangesMatchProperty(emoji_component_ranges, .emoji_component);
    try expectRangesMatchProperty(extended_pictographic_ranges, .extended_pictographic);
}

test "rangesFor returns the table matching each property" {
    try testing.expectEqual(emoji_ranges.ptr, rangesFor(.emoji).ptr);
    try testing.expectEqual(emoji_presentation_ranges.ptr, rangesFor(.emoji_presentation).ptr);
    try testing.expectEqual(emoji_modifier_ranges.ptr, rangesFor(.emoji_modifier).ptr);
    try testing.expectEqual(emoji_modifier_base_ranges.ptr, rangesFor(.emoji_modifier_base).ptr);
    try testing.expectEqual(emoji_component_ranges.ptr, rangesFor(.emoji_component).ptr);
    try testing.expectEqual(extended_pictographic_ranges.ptr, rangesFor(.extended_pictographic).ptr);
}

test "range tables are enumerable at comptime (consumer comptime resolution)" {
    // A consumer like a regex engine resolves \p{Emoji_Modifier} at comptime.
    const count = comptime blk: {
        var n: usize = 0;
        for (emoji_modifier_ranges) |r| n += r.end - r.start + 1;
        break :blk n;
    };
    try testing.expectEqual(@as(usize, 5), count); // the five skin-tone modifiers
}

test "emojiProperties: a multi-property code point reports every set field" {
    // U+231A WATCH: Emoji + Emoji_Presentation + Extended_Pictographic.
    const p = emojiProperties(0x231A);
    try testing.expect(p.emoji);
    try testing.expect(p.emoji_presentation);
    try testing.expect(p.extended_pictographic);
    try testing.expect(!p.emoji_modifier);
    try testing.expect(!p.emoji_modifier_base);
    try testing.expect(p.any());
}

test {
    testing.refAllDecls(@This());
}
